env:
  shared-node-browser: true
  commonjs: true
  mocha: true
  jest: true
  es6: true

extends:
  - eslint:recommended
  - llama
  - prettier

parser: babel-eslint
parserOptions:
  sourceType: module

rules:
  lines-around-comment: off
