#!/usr/bin/env bash
# Babel 7 changed their `--ignore` behavior with respect to `--copy-files`. If
# file copying is enabled, even those ignored will be included in dist/. This
# is problematic because Jest sees dist folders and tries to run them,
# breaking coverage.
function purge_test_files {
  find dist -type d -name __tests__ | while read -r test_dir; do
    rm -rf "$test_dir"
  done
}

find workspaces -maxdepth 1 -type d | while read -r pkg; do
  if [[ ! -f "$pkg/.babelrc" ]]; then
    continue
  fi

  pushd "$pkg" > /dev/null || exit 1
  printf 'Building %s... ' "$(basename "$pkg")"
  yarn run -s build
  purge_test_files
  popd > /dev/null || exit 1
done
