// flow-typed signature: a21b7ac36d8b120da0f1d065e62b2e44
// flow-typed version: <<STUB>>/minimalistic-assert_v^1.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minimalistic-assert'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minimalistic-assert' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'minimalistic-assert/index' {
  declare module.exports: $Exports<'minimalistic-assert'>;
}
declare module 'minimalistic-assert/index.js' {
  declare module.exports: $Exports<'minimalistic-assert'>;
}
